name: AnnouncerPlus-OG
version: '${version}'
main: xyz.jpenilla.announcerplus.AnnouncerPlus
description: A soft fork of AnnouncerPlus-OG maintained for TrueOG Network
authors: [jmp, NotAlexNoyle]
website: https://github.com/true-og/AnnouncerPlus-OG
api-version: '${apiVersion}'
depend:
  - LuckPerms
softdepend:
  - Essentials
  - ViaVersion
folia-supported: true
